### ISSUE TITLE
OTel not loaded!

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/Office-Addin-TaskPane-Angular-JS#34]
Hi everyone!

I built an Excel task pane add-in using Angular from the given template and didn't even write or modify any code. However, after uploading the manifest file, I got an error message regarding "OTel not loaded!" from excel-web-16.00.js file (a CDN from Microsoft). So, I was wondering if you guys could let me know how to fix this problem or help me out.

Attached is a screenshot of this error.

Thank you for your time and consideration!

![Screen Shot 2562-10-15 at 17 36 17](https://user-images.githubusercontent.com/18175994/66824636-de83ca80-ef72-11e9-909f-9ac14d57a07f.png)

**Comment by LouMM** [comment]
This should be resolved, please try again.
